from enum import Enum

ESTABLISH_CONNECTION_CODE = -1
CONNECTION_ESTABLISHMENT_INTERVAL = 0.5
CONNECTION_TIMEOUT = 1
WINDOW_SIZE = 5
TIMEOUT_GO_BACK_N_SENDER = 0.2  # sec
TIMEOUT_SEL_REPEAT_SENDER = 0.2
# MAX_LAST_PACKET_SENDING = 1
# TIMEOUT_LAST_PACKET_SENDER = 0.5
TIMEOUT_RECEIVER = 0.2
ERROR_PROBABILITY = 0.1

TRANSMISSION_TIMEOUT = 5


class TransmissionProtocol(Enum):
    ALGORITHM_TYPE_GBN = 1
    ALGORITHM_TYPE_SR = 2


# TRANSMISSION_PROTOCOL_TYPE = TransmissionProtocol.ALGORITHM_TYPE_GBN
TRANSMISSION_PROTOCOL_TYPE = TransmissionProtocol.ALGORITHM_TYPE_SR

# Network parameters
GRAPH_SYNC_TIME = 3
GRAPH_SYNC_TIME_INTERVAL = 10
NODE_LIFETIME = 40
HELLO_TIMEOUT = 3
DESIGNATED_NODE_LIFETIME = 60
NODES_NUMBER = 5
DISTANCE_THRESHOLD = 4

NETWORK_TIMEOUT = 90


class TopologyType(Enum):
    TOPOLOGY_STAR = 1
    TOPOLOGY_RING = 2
    TOPOLOGY_RANDOM = 3


# TOPOLOGY_TYPE = TopologyType.TOPOLOGY_STAR
TOPOLOGY_TYPE = TopologyType.TOPOLOGY_RING
# TOPOLOGY_TYPE = TopologyType.TOPOLOGY_RANDOM
