from enum import Enum

ESTABLISH_CONNECTION_CODE = -1
CONNECTION_ESTABLISHMENT_INTERVAL = 2
WINDOW_SIZE = 5
TIMEOUT_GO_BACK_N_SENDER = 2  # sec
TIMEOUT_SEL_REPEAT_SENDER = 2
MAX_LAST_PACKET_SENDING = 20
TIMEOUT_RECEIVER = 5
ERROR_PROBABILITY = 0.5


class TransmissionProtocol(Enum):
    ALGORITHM_TYPE_GBN = 1
    ALGORITHM_TYPE_SR = 2


# TRANSMISSION_PROTOCOL_TYPE = TransmissionProtocol.ALGORITHM_TYPE_GBN
TRANSMISSION_PROTOCOL_TYPE = TransmissionProtocol.ALGORITHM_TYPE_SR
